# Production overrides
# Usage: docker compose -f compose.yaml -f compose.prod.yaml up -d
#
# WARNING: This file contains production settings
# - Xdebug is disabled
# - Development tools are removed
# - Security is enhanced
# - Performance is optimized

services:
  php:
    restart: always

    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      XDEBUG_MODE: off

    # Don't expose Xdebug port in production
    ports: []

    # Optimize for production
    volumes:
      - .:/var/www/html:ro
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - symfony_var:/var/www/html/var

  nginx:
    restart: always

    # Read-only in production
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx

  mysql:
    restart: always

    # Don't expose MySQL port externally in production
    ports: []

    environment:
      # Use strong password from environment
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_INNODB_BUFFER_POOL_SIZE: 1G

    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=500
      --innodb-buffer-pool-size=1G
      --innodb-log-file-size=256M
      --innodb-flush-log-at-trx-commit=2
      --innodb-flush-method=O_DIRECT

  redis:
    restart: always

    # Don't expose Redis port externally
    ports: []

    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --requirepass ${REDIS_PASSWORD:-changeme}

  # Remove development tools
  mailpit:
    profiles:
      - dev

  adminer:
    profiles:
      - dev
