# macOS-specific optimizations
# Usage: docker compose -f compose.yaml -f compose.macos.yaml up -d
#
# This file provides optimizations for Docker Desktop on macOS:
# - Delegated/cached mount options for better I/O performance
# - Named volumes for vendor and var directories
# - Platform-specific settings for Apple Silicon (M1/M2/M3)

services:
  php:
    # Use delegated for better write performance on macOS
    volumes:
      - .:/var/www/html:delegated
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      # Use named volume only for var (cache/logs)
      - symfony_var:/var/www/html/var

    environment:
      # macOS-specific Xdebug settings
      XDEBUG_CONFIG: client_host=host.docker.internal discover_client_host=0

  nginx:
    volumes:
      # Cached mode for read-heavy operations
      - .:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    # Use ARM64 platform for Apple Silicon
    # Comment this out if you're on Intel Mac
    platform: linux/arm64/v8

    # Reduce buffer pool size on macOS to save memory
    environment:
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M

volumes:
  symfony_var:
    driver: local
